### ISSUE TITLE
Should we rename attribute accountId to clientId?

### ISSUE THREAD

**Issue by bensandoval** [PDFlex/pdflex-backend#13]
![image](https://github.com/PDFlex/pdflex-backend/assets/99620362/2e265327-8258-4e01-bc5a-6747ba5b97f3)

Just for the sake of consistency. If we get 2 more people to agree, then I will refactor (change) it.

**Comment by jiyapatel4** [comment]
Good catch. I believe in the `vithu-dao-creation` branch, accountId was renamed to clientId. But if you're just referring to the UML diagram, then please go ahead with the change!

**Comment by bensandoval** [comment]
Oh, thats amazing. thanks for letting me know jiya!
